name: Deploy Website

# Trigger the workflow only when pushing to the main branch
on:
  push:
    branches: [main]

jobs:
  deploy:
    # Run this job on the latest Ubuntu environment
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 5: Configure AWS credentials using secrets stored in GitHub
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Replace with your actual region

      # Step 2: Set up Node.js environment (adjust version if needed)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure this matches the Node.js version used in your project

      # Step 3: Install project dependencies from package-lock.json (more reliable than `npm install`)
      - name: Install dependencies
        run: npm ci

      # Step 4: Build the Vite project for production (output goes into `dist/`)
      - name: Build Application
        run: npm run build

      # Step 6: Sync the built files in `dist/` to your S3 bucket
      - name: Deploy to S3
        run: aws s3 sync ./build s3://${{secrets.BUCKET_NAME}}

      - name: Create Cloudfront Invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.DISTRIBUTION_ID}} --paths "/*"
